### ISSUE TITLE
n must be smaller than the index type max value

### ISSUE THREAD

**Issue by ShallMate** [Visa-Research/volepsi#12]
Professor, I recently learned to run OKVS in RR22. When I run the function perfPaxosImpl<8>. I use -n 1000000 to try to build an OKVS with n=1000000. But it told me: n must be smaller than the index type max value. How to solve this?

**Comment by ShallMate** [comment]
Ok, I should use <64> to run it. But I don't quite understand why? Professor can you explain briefly?

**Comment by ladnir** [comment]
Running time? Use silver... Read the program command line help info.

Okvs with u8? As an optimization you can use a u8 as an index for the okvs. As such, your index can have values between 0 and 255. This works great if you don't exceed this range. However, n=1000000 clearly would require indexing beyond this. u32 should always work. In some cases u16 should work.

Smaller index get better running time due to it taking up less memory and getting better cache utilization.

**Comment by ShallMate** [comment]
OK, Professor. But are Silver and OKVS also connected? What I read in the paper is that Silver is the encoding of VOLE. But what I want to run is OKVS. If I run PSI, then I can directly use setMultType(oc::MultType::slv5) to make Silent VOLE use Silver encoding. But I just want to run the encoding and decoding of OKVS, is this also related to Silver? Because I actually just run perfPaxosImpl<u32>(cmd), and its total running time is 3.5 seconds. If Silver can also optimize OKVS, then how can I set the encoding of OKVS to Silver, just like setMultType(oc::MultType::slv5).

**Comment by ladnir** [comment]
Silver is not related to okvs. If you want okvs then you can forget about silver. You should use Baxos, not Paxos.

**Comment by ladnir** [comment]
Silver makes the psi faster. Baxos makes the paxos faster. Baxos is paxos with with the binning optimization

**Comment by ShallMate** [comment]
But, prof. I also tried running the perfBaxos function, which is supposed to run Baxos. but. It still takes me about 3.3 seconds to complete -n 1000000 encoding and decoding. is this normal? Because the whole PSI doesn't take so long, does it? But this is just a sub-process of PSI.

**Comment by ladnir** [comment]
No, that doesn't seem normal. Hard to say what the problem is...

You can add -v to see if encode or decode is slow.

PS, I'm not a professor ;)

**Comment by ShallMate** [comment]
OK, I'll try again with -v. By the way, what should I call you? thanks for your help.

**Comment by ShallMate** [comment]
Hello, let me call you Dr. Peter for now. I used -v parameter. Got the following result. Does this show where the problem is?
![2022-12-22 23-27-56屏幕截图](https://user-images.githubusercontent.com/25976948/209080945-f48693e2-f8d0-4e61-80ea-153f0c5cd111.png)

**Comment by ladnir** [comment]
No ha. Are you on a slow computer? Did you build with debug?

**Comment by ShallMate** [comment]
No, I'm not running on a very slow computer. Because I only want to run OKVS, and I have installed libOTE and related dependencies locally. I directly separated the source code part of OKVS from volePSI. That is, OKVS is compiled separately, but I don't think this should have an impact on performance, right?

**Comment by ladnir** [comment]
When you built libOTe was sse enabled? You can see this by calling the libOTe build.py and look for ENABLE_SSE.

Did you build your code in release mode?

**Comment by ShallMate** [comment]
我执行了 cmake -DCMAKE_BUILD_TYPE=Release 。 . 然后时间缩短到0.7s，非常感谢。 这与论文中非集群模式下OKVS的效率相当。 集群不起作用？ 我可以在编译 libOTE 时启用 SSE 来启动集群吗？

**Comment by ShallMate** [comment]
I executed cmake -DCMAKE_BUILD_TYPE=Release . . Then the time was shortened to 0.7s, thank you very much. This is comparable to the efficiency of OKVS in non-clustering mode in the paper. Is clustering not working? Can I start clustering with enable SSE when compiling libOTE?

**Comment by ladnir** [comment]
Clustering is Baxos.

Sse just makes it faster in general.

**Comment by ShallMate** [comment]
OK, thank you very much. Dr. Peter.
