### ISSUE TITLE
perform  [manually] 

### ISSUE THREAD

**Issue by HelloLtc** [Visa-Research/volepsi#15]
Hi authors, I recently tried to run the example on how to perform  [manually] get & send the protocol messages. 
And I want to obtain the intersection results from the recevier, however it shows that the intersection size is 0 when I  use ./frontend -messagePassing. 

Code:
        // that it need to receive a message from the other party.
        auto protocol = recevier.run(set, sock) | macoro::make_eager();
        // Perform the communication and complete the protocol.
        communicate(protocol, false, sock, verbose);
        **std::cout << "size:"<< recevier.mIntersection.size()<<std::endl;**
        std::cout << "recver done\n";

Output:
     sender done
     size:0
     recver done

 I think its size should be 100, but it is 0. I dont know whither I made a mistake？

**Comment by ladnir** [comment]
yes, there appears to be a bug. I'll look into it

**Comment by RindalVisa** [comment]
pushed a fix. There was a new feature to reduce the round complexity from 6 rounds to 3 but that doesnt appear to be working correctly. Turned off the feature and everything is working. This feature is off if the last parameter to setup is false. See here. https://github.com/Visa-Research/volepsi/blob/main/frontend/messagePassingExample.h#L153

**Comment by ladnir** [comment]
Also fixed the feature issue of using fewer rounds. See this option https://github.com/Visa-Research/volepsi/blob/main/frontend/messagePassingExample.h#L136

When set, the protocol does a bit more work but required fewer messages to be sent.
