### ISSUE TITLE
how to get a dynamic link library about volepsi

### ISSUE THREAD

**Issue by TY-cc** [Visa-Research/volepsi#16]
I want to get a dynamic link library. I modifed STATIC to SHARED at the file of volepsi/volePSI/cmakelists.txt.
it report error as follow:

> /usr/bin/ld: /home/cc/VOLE/volepsi-main/out/install/linux/lib/liblibOTe.a(Mtx.cpp.o): relocation R_X86_64_PC32 against symbol `_ZSt4cout@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status

**Comment by ladnir** [comment]
set `VOLE_PSI_PIC` to be true. https://github.com/Visa-Research/volepsi/blob/main/cmake/buildOptions.cmake#L46. i.e.

`cmake -DVOLE_PSI_PIC=true ...` or `python3 -DVOLE_PSI_PIC=true`

**Comment by TY-cc** [comment]
Thank you. I have try to use this way, but report error as follow:

> [ 13%] Linking CXX shared library libvolePSI.so
/usr/bin/ld: /home/cc/VOLE/volepsi-main/out/install/linux/lib/libcoproto.a(SocketScheduler.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt12system_error@@GLIBCXX_3.4.11' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status


On the other hand，I have a problem. I try to set "-fPIC" about sub-library,  they have "libOTe.a", "libcrytoTools.a", and "libcoproto.a".  I added the instruction ' set _ property ( TARGET XXX PROPERTY POSITION _ INDEPENDENT _ CODE ON ) ' to their cmake file, the libOTe.a and libcrytoTools.a compile success, but the libcoproto.a report same error. why?

**Comment by TY-cc** [comment]
I cleaned up the previous installation using “`--clean`” and rebuilt it using “`python3 build.py-DCOPROTO _ ENABLE _ BOOST = ON-DCOPROTO _ ENABLE _ OPENSSL = ON-DVOLE _ PSI _ PIC = true`”. A new error occurred, but the error type is the same

> /usr/bin/ld: /home/cc/VOLE/volepsi-main/out/install/linux/lib/libbitpolymul.a(bc.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN3bpm6_sh_opE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status

**Comment by ladnir** [comment]
yeah, that one might be a bit tricky. That library has assembly in it and I'm not totally sure if we can set PIC for it. But we can try,

in `out/bitpolymul/bitpolymul/CMakeLists.txt`, you can add `-fPIC` to the `target_compile_options` command. You will then need to delete

`out/install`
`out/libOTe/out/install`

and then call `python3 build.py`

**Comment by TY-cc** [comment]
Cool, your method succeeded. I tried  add '`add _ compile _ options ( -fPIC )` ' in `/bitpolymul/bitpolymul/CMakeLists.txt`, but it was useless. Here, `-fPIC` must be added to `target _ compile _ options`. 
Thank you for your reply

**Comment by ladnir** [comment]
Great, we can leave this open and when I have time I'll fix this in bitpolymul and close it.

**Comment by TY-cc** [comment]
All right, listen to your arrangement. Thanks again

**Comment by RindalVisa** [comment]
ok. the PIC flag should now hopefully work better. Changed the option name to `VOLE_PSI_ENABLE_PIC` but i think `VOLE_PSI_PIC` should still work. See the readme.

**Comment by ladnir** [comment]
I doubt that's what you actually want to do. Why would you want to remove it?

If you really want to know it's in cmake I believe.

**Comment by TY-cc** [comment]
I wrote a new interface in the dynamic library to facilitate my own call. But this requires a link soft link can be done. I know that the library 's version information is in the `vole-main / volepsi / cmakelist` file, please forgive me for trying to get lazy. Sorry

**Comment by ladnir** [comment]
OK, glad you figured it out
