### ISSUE TITLE
Is there something wrong with the derivation of OKVS in the paper "Blazing Fast PSI from Improved OKVS and Subfield VOLE"

### ISSUE THREAD

**Issue by CN-HYC** [Visa-Research/volepsi#21]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/53418389/220546510-b8b182d7-2b01-49d9-bffb-a1857445eec6.png">

And what I came up with is this

<img width="167" alt="image" src="https://user-images.githubusercontent.com/53418389/220546879-b57cc277-0af4-4275-bcbe-2e24cbf88742.png">
I don't know if there is a problem in my link. I hope you can get an answer. Thank you very much.

**Comment by ladnir** [comment]
The original seems right but I could be wrong. The idea is that your simply undoing the permutation pi^c

**Comment by CN-HYC** [comment]
OK,I see what you mean,Thank you for your answer.
