### ISSUE TITLE
error when building Sodium

### ISSUE THREAD

**Issue by EverVio1et** [Visa-Research/volepsi#22]
<img width="405" alt="1677312872571" src="https://user-images.githubusercontent.com/103190692/221346881-a5607c14-3a61-496f-9e67-59af9c1ffe16.png">

I have tried this result many times.

**Comment by ladnir** [comment]
The error tells you the problem. libtool is required but want found. You need to install it. apt install libtool

**Comment by EverVio1et** [comment]
Thanks, I have compiled successfully.
