### ISSUE TITLE
some problems about mDenseSize in PaXoS

### ISSUE THREAD

**Issue by Xie610** [Visa-Research/volepsi#24]
It seems that there are some data overflow problems in the code of PaxosImpl.h , as mDenseSize is not always less than 64, for example when mWeight=2 and mDt=binary. However, some operations such as the variable denseMasks, the function decode32 and backfillBinary, appear to assume that mDenseSize is less than 64. I also noticed the assert statement, but it doesn't seem to be working due to the "-DNDEBUG" setting. When I removed this setting, I saw the following error message.
![image](https://user-images.githubusercontent.com/105502241/222439972-db0360d1-3f5d-421b-80f0-2cacc13f37d9.png)
If you could respond to this issue, I would greatly appreciate it.

**Comment by Xie610** [comment]
Perhaps segmenting the data or continuing to use the BitIterator can help with this problem.

**Comment by ladnir** [comment]
Why do you want to use w=2?

**Comment by Xie610** [comment]
I just happened to come across and discovered this phenomenon while studying the algorithm and conducting tests, without any particular reason to use it, just for the purpose of testing.
