### ISSUE TITLE
					 How to revert to string after hash to block

### ISSUE THREAD

**Issue by yellow123Nike** [Visa-Research/volepsi#27]
How to revert to string after hash to block？
<img width="308" alt="image" src="https://user-images.githubusercontent.com/37546857/224627697-0cae4682-c7d7-40d3-bf66-84cf208a06fa.png">

**Comment by ladnir** [comment]
I'm not sure what you mean

**Comment by yellow123Nike** [comment]
Hello, Professor. I am using OPRF with labels. read the file as follows；
<img width="286" alt="image" src="https://user-images.githubusercontent.com/37546857/224636022-ab30f809-e857-4353-8006-cdcf2f83bd1f.png">
I then got the following error when running the opprf protocol:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/37546857/224636162-5c0ff7a7-97e1-4973-a274-1aeddd4c9244.png"
I don't have the above problem when my label type is std::vector<block>. But when the type is oc::Matrix<u8>, there is a communication problem

**Comment by ladnir** [comment]
I'm not sure about details of your code but the receive buffer size does not match the size of the data that was send.

**Comment by yellow123Nike** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/37546857/224637861-b7f9f95e-d536-4704-8011-0eb0967e0eab.png">
I didn't change the code, I just replaced the label. The original label：
<img width="265" alt="image" src="https://user-images.githubusercontent.com/37546857/224638184-1630de49-b486-4baf-b7a6-7f9193401468.png">
My replacement is as follows：
<img width="305" alt="image" src="https://user-images.githubusercontent.com/37546857/224638476-22ced5cc-5e57-4e82-95a7-7ffe588f0dd4.png">

**Comment by ladnir** [comment]
Yeah, I'm not following. You'll have to explain in more detail

**Comment by yellow123Nike** [comment]
Well, thank you, excuse me. I'll think about it.

**Comment by yellow123Nike** [comment]
A string is stored as a block type by：
`
string str="hello";
block ab;
hash.Reset();
hash.Update(str.data(), str.size());
hash.Final(ab);`
How to revert ab(block) to str(string) again

**Comment by ladnir** [comment]
You can't. That's the whole point of a hash function. It's a one way function. The only way to invert it is to guess the input and check it by rehashing.

**Comment by yellow123Nike** [comment]
So can I convert string to block storage directly and how can I block convert to string?
`string str="hello";
block ab=fun1(str);
string str2=fun2(str);
`
cout<<str2；
”hello“
Is this possible?

**Comment by ladnir** [comment]
Taking a step back, what do you want to accomplish? You want to have an opprf where you program the output to be something other than a block? You want it to be some special string?

**Comment by yellow123Nike** [comment]
I want to implement PSI with labels via opprf. I have now completed the basic tests. But how do I revert to the original after the receiver gets the hash processed label in the last step?

**Comment by yellow123Nike** [comment]
yey!I made it!thanks
