### ISSUE TITLE
some problem about your OPPRF

### ISSUE THREAD

**Issue by L-coder148** [Visa-Research/volepsi#28]
Hi,

For a project, I need to implement the malicious OPPRF that is against both malicious sender and receiver,  I was going to use the PAXOS and OOS OT to implement that using the [cryptobiu/PaXoS_PSI](https://github.com/cryptobiu/PaXoS_PSI) before, their code is very clear, but I'm unfamiliar with their programming style

And I have always used your library libPSI and very like your programming style. And your reply to the issues is very timely. Today, I see this paper vole-psi, which achieves malicious security, but I have not read the paper completely for time concern,  it seems that your RSOPPRF can satisfy my needs, I want to first confirm that whether your RSOPPRF.h is malicious against both malicious sender and receiver, can I use that to achieve my aim. I'm sorry to bother you before I have fully read the paper.

Thank you!

**Comment by ladnir** [comment]
Yes, it's secure

**Comment by ladnir** [comment]
you will need to set https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOprf.h#L25 to be true on the OPRF that is used by the OPPRF https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOpprf.h#L93

Otherwise is should be malicious secure.

**Comment by L-coder148** [comment]
OK, thank you!

**Comment by L-coder148** [comment]
Hi,

I use the RsOPPRF.h, it seems that if the OPPRF sender's setsize is not equal to the OPPRF receiver's setsize, the program will jam and has no output. Can RsOPPRF support the setsize of Sender and receiver is not equal. For example: one is 100,one is 1000.

Thanks!

**Comment by ladnir** [comment]
It's possible I didn't test that case and there is a bug. I'll take a look when I find time.

**Comment by L-coder148** [comment]
Thank you for your reply, what's more, I want to know the difference between the fucntion `RsOpprf_eval_blk_test` and `RsOpprf_eval_blk_mtx_test` in `RsOpprf_Tests.h`, what does `mtx `means?

**Comment by L-coder148** [comment]
> you will need to set https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOprf.h#L25 to be true on the OPRF that is used by the OPPRF https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOpprf.h#L93
> 
> Otherwise is should be malicious secure.

To achieve malicious security against both parties， I set both the OPRF sender https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOprf.h#L25 and OPRF receiver https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOprf.h#L51 to be true.
