### ISSUE TITLE
run this repo just like libpsi？

### ISSUE THREAD

**Issue by nihaoqingtuan** [Visa-Research/volepsi#3]
libpsi can run through /libPSI/out/build/linux/frontend/. volepsi is also started through the executable file of this path  /volepsi/out/build/linux/frontend/, right？

**Comment by ladnir** [comment]
thats correct

**Comment by nihaoqingtuan** [comment]
But when I run the executable, only the test case shows pass, and using -help doesn't give command help like libpsi does.

**Comment by ladnir** [comment]
Take a look at main. Should be pretty self explanatory. There an example where protocol messages are manually passed between parties by writing the messages to files and having other other party read the file. This example demonstrates how to pass messaged if you don't want to use something like a network socket. 

There is also the performance benchmark code that computes the running time. This uses a custom socket for communication that only works within a single program, ie no tcp/ip socket. 

As previously mentioned, I will be adding another example with tls support over tcp/ip. 

https://github.com/Visa-Research/volepsi/blob/74404b7a97d97a92531cc7d106c2a8af87c4c0b9/frontend/main.cpp#L146

**Comment by nihaoqingtuan** [comment]
i get it. so i have to write it myself. thanks

**Comment by ladnir** [comment]
What are you trying to achieve?

**Comment by nihaoqingtuan** [comment]
I tried testing the performance metrics of this psi and I thought it would be as easy as testing using libpsi.

**Comment by ladnir** [comment]
It should be easy to get performance numbers. Call frontend with

`-perf -psi`

You can get log2 of the set size using `-nn 10`. This would run the psi with 2^10 items per set. Here area few other parameters you can set. See here
 https://github.com/Visa-Research/volepsi/blob/74404b7a97d97a92531cc7d106c2a8af87c4c0b9/frontend/perf.cpp#L347

**Comment by nihaoqingtuan** [comment]
i start to try it. And i want to know if the command of this library has help,just like libpsi.

**Comment by nihaoqingtuan** [comment]
i get it. This repo doesn't yet allow us to import data files ourselves like libpsi does. The project has not yet been implemented

**Comment by ladnir** [comment]
No, but could be added. Will be updating the code this weekend most likely.

**Comment by RindalVisa** [comment]
ok, you should be able to do everything you want now. There is a help section for frontend. You can do the PSI using a file as your set and you can now run everything over tls.

**Comment by nihaoqingtuan** [comment]
ok, i just update volepsi. But when i use ./frontend -in /home/db/alice.csv -csv -r 0
there is a question:
connecting as client at address localhost:1212Exception: COPROTO_ENABLE_BOOST must be define (via cmake) to use tcp sockets. /home/db/PSI/volepsi/volePSI/fileBased.cpp:347

**Comment by RindalVisa** [comment]
```
git pull
python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON --clean
```

**Comment by ladnir** [comment]
The default behavior is to look boost on the system and if not found then to automatically download it for you. Are you getting issues with boost?

**Comment by nihaoqingtuan** [comment]
i use "python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON",but it doesn't work.

**Comment by ladnir** [comment]
Did you use `--clean`?

**Comment by nihaoqingtuan** [comment]
CMake Error: Unknown argument --clean

**Comment by ladnir** [comment]
```
git pull
python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON --clean 
```

**Comment by nihaoqingtuan** [comment]
i clone volepsi again and build libOTe,then i meet issue again.

./tests/libcoproto_tests.a(AsioTlsSocket_tests.cpp.o): In function 'coproto::tests::AsioTlsSocket_Accept_test()':
AsioTlsSocket_tests.cpp: (.text+0x5677): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56e8): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56fe): undefined reference to 'SSL_get1_peer_certificate'
collect2: error: ld returned 1
gmake[2]: *** [frontend/CMakeFiles/frontend.dir/build.make:153:frontend/frontend] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:187:frontend/CMakeFiles/frontend.dir/all] Error 2
gmake: *** [Makefile:136:all] Error 2

**Comment by ladnir** [comment]
What OS are you on?

**Comment by nihaoqingtuan** [comment]
linux



---- Replied Message ----
| From | Peter ***@***.***> |
| Date | 11/01/2022 11:40 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [Visa-Research/volepsi] run this repo just like libpsi？ (Issue #3) |

What OS are you on?

**Comment by ladnir** [comment]
Assuming linux means Ubuntu `sudo apt-get install openssl openssl-dev`

**Comment by nihaoqingtuan** [comment]
i have downloaded openssl.

**Comment by nihaoqingtuan** [comment]
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)

**Comment by nihaoqingtuan** [comment]
maybe it's not openssl. I reloaded volepsi yesterday and there was no such thing, just a mistake at the beginning. After re-downloading and pulling again today, there is this problem.

i will try to delete all clean

**Comment by nihaoqingtuan** [comment]
I re-downloaded volepsi and followed these steps to compile:
git clone volepsi
cd volepsi/thirdparty
git clone libOTe
cd libOTe
python3 build.py -D FETCH_SODIUM=true --setup
cd ../..
python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON --clean 

But there is a problem：
CMake Error at cmake/findDependancies.cmake:58 (find_package):
  By not providing "FindlibOTe.cmake" in CMAKE_MODULE_PATH this project has                                                                                                                   
  asked CMake to find a package configuration file provided by "libOTe", but                                                                                                                  
  CMake did not find one.                                                                                                                                                                     
                                                                                                                                                                                              
  Could not find a package configuration file provided by "libOTe" with any                                                                                                                   
  of the following names:                                                                                                                                                                     
                                                                                                                                                                                              
    libOTeConfig.cmake                                                                                                                                                                        
    libote-config.cmake                                                                                                                                                                       
                                                                                                                                                                                              
  Add the installation prefix of "libOTe" to CMAKE_PREFIX_PATH or set                                                                                                                         
  "libOTe_DIR" to a directory containing one of the above files.  If "libOTe"                                                                                                                 
  provides a separate development package or SDK, be sure it has been                                                                                                                         
  installed.                                                                                                                                                                                  
Call Stack (most recent call first):                                                                                                                                                          
  cmake/findDependancies.cmake:72 (FIND_LIBOTE)                                                                                                                                               
  CMakeLists.txt:13 (include)    

then i build libOTe alone. the problem is that:
[100%] Linking CXX executable frontend
./tests/libcoproto_tests.a(AsioTlsSocket_tests.cpp.o): In function 'coproto::tests::AsioTlsSocket_Accept_test()':
AsioTlsSocket_tests.cpp: (.text+0x5677): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56e8): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56fe): undefined reference to 'SSL_get1_peer_certificate'
collect2: error: ld returned 1
gmake[2]: *** [frontend/CMakeFiles/frontend.dir/build.make:153:frontend/frontend] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:187:frontend/CMakeFiles/frontend.dir/all] Error 2
gmake: *** [Makefile:136:all] Error 2
CMake Error at thirdparty/fetch.cmake:34 (message):
  Build failed (2).                                                                                                                                                                           
                                                                                                                                                                                              
  LOG:                                                                                                                                                                                        
                                                                                                                                                                                              
Call Stack (most recent call first):                                                                                                                                                          
  thirdparty/getCoproto.cmake:39 (run)                                                                                                                                                        
  cmake/libOTeDepHelper.cmake:65 (include)                                                                                                                                                    
  CMakeLists.txt:66 (include)

**Comment by ladnir** [comment]
Should be as the readme says:
```
git clone https://github.com/Visa-Research/volepsi.git
cd volepsi
python3 build.py  -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON
```

**Comment by nihaoqingtuan** [comment]
this time i just build volepsi. But it also fail.

../tests/libcoproto_tests.a(AsioTlsSocket_tests.cpp.o): In function 'coproto::tests::AsioTlsSocket_Accept_test()':
AsioTlsSocket_tests.cpp: (.text+0x5677): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56e8): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56fe): undefined reference to 'SSL_get1_peer_certificate'
collect2: error: ld returned 1
gmake[2]: *** [frontend/CMakeFiles/frontend.dir/build.make:153:frontend/frontend] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:187:frontend/CMakeFiles/frontend.dir/all] Error 2
gmake: *** [Makefile:136:all] Error 2
CMake Error at thirdparty/fetch.cmake:34 (message):
  Build failed (2).

  LOG:

Call Stack (most recent call first):
  thirdparty/getCoproto.cmake:39 (run)
  cmake/libOTeDepHelper.cmake:65 (include)
  CMakeLists.txt:66 (include)


-- Configuring incomplete, errors occurred!
See also "/home/db/zpsi/volepsi/thirdparty/libOTe/out/build/linux/CMakeFiles/CMakeOutput.log".
libOTe Build
'/usr/cmake-3.24.0-rc2-linux-x86_64/bin/cmake' '--build' '/home/db/zpsi/volepsi/thirdparty/libOTe/out/build/linux' ' --config' 'Release'
gmake: Makefile: No such file or directory
gmake: *** No rules to make target 'Makefile'. stop.
libOTe Install
'/usr/cmake-3.24.0-rc2-linux-x86_64/bin/cmake' '--install' '/home/db/zpsi/volepsi/thirdparty/libOTe/out/build/linux' ' --config' 'Release' '--prefix' '/home/db/zpsi/volepsi/out/install/linux'
CMake Error: Error processing file: /home/db/zpsi/volepsi/thirdparty/libOTe/out/build/linux/cmake_install.cmake
log /home/db/zpsi/volepsi/thirdparty/log-libOTe.txt
=============================================
CMake Error at cmake/findDependancies.cmake:58 (find_package):
  By not providing "FindlibOTe.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libOTe", but
  CMake did not find one.
                                                                                                                                                                                              
  Could not find a package configuration file provided by "libOTe" with any
  of the following names:
                                                                                                                                                                                              
    libOTeConfig.cmake
    libote-config.cmake
                                                                                                                                                                                              
  Add the installation prefix of "libOTe" to CMAKE_PREFIX_PATH or set
  "libOTe_DIR" to a directory containing one of the above files. If "libOTe"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/findDependancies.cmake:72 (FIND_LIBOTE)
  CMakeLists.txt:13 (include)

**Comment by ladnir** [comment]
Please post the full output of
```
cd .\thirdparty\libOTe\thirdparty\coproto\
python3 .\build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON
```

**Comment by nihaoqingtuan** [comment]
[db@LIN-4C855C1D01E volepsi]$ cd thirdparty/libOTe/thirdparty/coproto
[db@LIN-4C855C1D01E coproto]$ python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON


====== build.py (coproto) ========
mkdir -p out/build/linux
cmake -S . -B out/build/linux -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON -DCOPROTO_FETCH_AUTO=ON -DCMAKE_BUILD_TYPE=Release
cmake --build out/build/linux --parallel 6
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


-- Option: COPROTO_STAGE = /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux
-- Option: CMAKE_INSTALL_PREFIX = /usr/local
--Option: CMAKE_BUILD_TYPE=Release
        Release
        Debug
        RELWITHDEBINFO
-- Option: COPROTO_FETCH_AUTO = ON
-- Option: COPROTO_FETCH_SPAN =
-- Option: COPROTO_FETCH_FUNCTION2 =
-- Option: COPROTO_FETCH_MACORO =
-- Option: COPROTO_FETCH_BOOST =

--Option: COPROTO_CPP_VER = 14
-- Option: COPROTO_ENABLE_BOOST = ON
-- Option: COPROTO_ENABLE_OPENSSL = ON
-- Option: COPROTO_ENABLE_ASSERTS = ON

-- Option: COPROTO_STAGE = /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux
-- Option: COPROTO_STAGE = /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux
span-lite already fetched.
macoroConfig.cmake : /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux/lib64/cmake/macoro/macoroConfig.cmake
macoro already fetched.
macoroConfig.cmake : /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux/lib64/cmake/macoro/macoroConfig.cmake
function2 already fetched.
Boost already fetched.
-- Boost_LIB: Boost::system;Boost::thread;Boost::regex
--Boost_INC:


-- Configuring done
-- Generating done
-- Build files have been written to: /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/build/linux
Consolidate compiler generated dependencies of target coproto
[ 26%] Built target coproto
Consolidate compiler generated dependencies of target coproto_tests
[ 78%] Built target coproto_tests
Consolidate compiler generated dependencies of target frontend
[ 82%] Linking CXX executable frontend
../tests/libcoproto_tests.a(AsioTlsSocket_tests.cpp.o): In function 'coproto::tests::AsioTlsSocket_Accept_test()':
AsioTlsSocket_tests.cpp: (.text+0x5677): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56e8): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56fe): undefined reference to 'SSL_get1_peer_certificate'
collect2: error: ld returned 1
gmake[2]: *** [frontend/CMakeFiles/frontend.dir/build.make:153:frontend/frontend] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:187:frontend/CMakeFiles/frontend.dir/all] Error 2
gmake: *** [Makefile:136:all] Error 2

**Comment by ladnir** [comment]
From that folder (coproto), can you remove the out/ folder and rerun build.py and post the result.

I'm a bit confused about this error. It appears you have openssl but you can't linking the openssl library.

**Comment by nihaoqingtuan** [comment]
[8%] Building CXX object coproto/CMakeFiles/coproto.dir/Common/error_code.cpp.o
[8%] Building CXX object coproto/CMakeFiles/coproto.dir/Common/CLP.cpp.o
[ 13%] Building CXX object coproto/CMakeFiles/coproto.dir/Common/Util.cpp.o
[ 17%] Building CXX object coproto/CMakeFiles/coproto.dir/Socket/SocketScheduler.cpp.o
[ 21%] Building CXX object coproto/CMakeFiles/coproto.dir/Socket/AsioSocket.cpp.o
[ 26%] Linking CXX static library libcoproto.a
[ 26%] Built target coproto
[ 34%] Building CXX object tests/CMakeFiles/coproto_tests.dir/BufferingSocket_tests.cpp.o
[ 39%] Building CXX object tests/CMakeFiles/coproto_tests.dir/AsioTlsSocket_tests.cpp.o
[ 34%] Building CXX object tests/CMakeFiles/coproto_tests.dir/AsioSocket_tests.cpp.o
[ 43%] Building CXX object tests/CMakeFiles/coproto_tests.dir/InlinePoly.cpp.o
[ 47%] Building CXX object tests/CMakeFiles/coproto_tests.dir/LocalAsyncSocket_tests.cpp.o
[ 52%] Building CXX object tests/CMakeFiles/coproto_tests.dir/Queue_tests.cpp.o
[ 56%] Building CXX object tests/CMakeFiles/coproto_tests.dir/SocketScheduler_tests.cpp.o
[ 60%] Building CXX object tests/CMakeFiles/coproto_tests.dir/TaskProto14_tests.cpp.o
[ 65%] Building CXX object tests/CMakeFiles/coproto_tests.dir/TaskProto_tests.cpp.o
[ 69%] Building CXX object tests/CMakeFiles/coproto_tests.dir/Tests.cpp.o
[ 73%] Building CXX object tests/CMakeFiles/coproto_tests.dir/TypeTraits.cpp.o
[ 78%] Linking CXX static library libcoproto_tests.a
[ 78%] Built target coproto_tests
[86%] Building CXX object frontend/CMakeFiles/frontend.dir/cpp14Tutorial.cpp.o
[86%] Building CXX object frontend/CMakeFiles/frontend.dir/SocketTutorial.cpp.o
[ 91%] Building CXX object frontend/CMakeFiles/frontend.dir/main.cpp.o
[ 95%] Building CXX object frontend/CMakeFiles/frontend.dir/cpp20Tutorial.cpp.o
[100%] Linking CXX executable frontend
../tests/libcoproto_tests.a(AsioTlsSocket_tests.cpp.o): In function 'coproto::tests::AsioTlsSocket_Accept_test()':
AsioTlsSocket_tests.cpp: (.text+0x5677): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56e8): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56fe): undefined reference to 'SSL_get1_peer_certificate'
collect2: error: ld returned 1
gmake[2]: *** [frontend/CMakeFiles/frontend.dir/build.make:153:frontend/frontend] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:187:frontend/CMakeFiles/frontend.dir/all] Error 2
gmake: *** [Makefile:136:all] Error 2

**Comment by ladnir** [comment]
And now `cmake --build out/build/linux --verbose `

**Comment by nihaoqingtuan** [comment]
[ 82%] Linking CXX executable frontend
cd /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/build/linux/frontend && /usr/cmake-3.24.0-rc2-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/frontend .dir/link.txt --verbose=1
/usr/local/bin/c++ -O3 -DNDEBUG CMakeFiles/frontend.dir/SocketTutorial.cpp.o CMakeFiles/frontend.dir/cpp14Tutorial.cpp.o CMakeFiles/frontend.dir/cpp20Tutorial.cpp.o CMakeFiles/frontend.dir /main.cpp.o -o frontend ../coproto/libcoproto.a ../tests/libcoproto_tests.a ../coproto/libcoproto.a /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/ out/install/linux/lib/libboost_system.a /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux/lib/libboost_thread.a /usr/lib64/libssl.so /usr/ lib64/libcrypto.so /home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/install/linux/lib64/libmacoro.a -lpthread
../tests/libcoproto_tests.a(AsioTlsSocket_tests.cpp.o): In function 'coproto::tests::AsioTlsSocket_Accept_test()':
AsioTlsSocket_tests.cpp: (.text+0x5677): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56e8): undefined reference to 'SSL_get1_peer_certificate'
AsioTlsSocket_tests.cpp:(.text+0x56fe): undefined reference to 'SSL_get1_peer_certificate'
collect2: error: ld returned 1
gmake[2]: *** [frontend/CMakeFiles/frontend.dir/build.make:153:frontend/frontend] Error 1
gmake[2]: leave directory "/home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/build/linux"
gmake[1]: *** [CMakeFiles/Makefile2:187:frontend/CMakeFiles/frontend.dir/all] Error 2
gmake[1]: leave directory "/home/db/zpsi/volepsi/thirdparty/libOTe/thirdparty/coproto/out/build/linux"
gmake: *** [Makefile:136:all] Error 2

**Comment by nihaoqingtuan** [comment]
i try to mv files.but:
[root@LIN-4C855C1D01E ~]# chmod 777 -fv /usr/lib64/libssl.*
Permission mode for '/usr/lib64/libssl.so' is reserved at 0777 (rwxrwxrwx)
Permission mode for '/usr/lib64/libssl.so.10' is reserved at 0777 (rwxrwxrwx)
Permission mode for '/usr/lib64/libssl.so.1.1' is reserved at 0777 (rwxrwxrwx)
Permission mode for '/usr/lib64/libssl.so.1.1.1o' is reserved at 0777 (rwxrwxrwx)
Permission mode for '/usr/lib64/libssl.so.3' is reserved at 0777 (rwxrwxrwx)
[root@LIN-4C855C1D01E ~]# mv /usr/lib64/libssl.* /usr/lib64/temp/
mv: cannot move '/usr/lib64/libssl.so' to '/usr/lib64/temp/libssl.so': operation not permitted
mv: cannot move '/usr/lib64/libssl.so.10' to '/usr/lib64/temp/libssl.so.10': operation not permitted
mv: cannot move '/usr/lib64/libssl.so.1.1' to '/usr/lib64/temp/libssl.so.1.1': Operation not permitted
mv: cannot move '/usr/lib64/libssl.so.1.1.1o' to '/usr/lib64/temp/libssl.so.1.1.1o': Operation not permitted
mv: cannot move '/usr/lib64/libssl.so.3' to '/usr/lib64/temp/libssl.so.3': operation not permitted

$ lsattr /usr/lib64/libssl.*
lsattr: unsupported operation while reading flags from /usr/lib64/libssl.so
------------------- /usr/lib64/libssl.so.10
lsattr: unsupported operation while reading flags in /usr/lib64/libssl.so.1.1
------------------- /usr/lib64/libssl.so.1.1.1o
lsattr: unsupported operation while reading flags in /usr/lib64/libssl.so.3

**Comment by nihaoqingtuan** [comment]
i remember that linux has openssl and i also download new openssl.

**Comment by nihaoqingtuan** [comment]
i can cp files but not mv. can i just use cp?

**Comment by ladnir** [comment]
Can you Uninstaller the apt-get version?

**Comment by nihaoqingtuan** [comment]
my os uses yum

**Comment by ladnir** [comment]
Well not sure. You can try to Uninstaller your version of openssl. Or you can use a docker/contain/vm.

**Comment by nihaoqingtuan** [comment]
i will try again
