### ISSUE TITLE
Hi Professor, I am not very familiar with c++, but I want to implement asynchronous operations, but MC_AWAIT reports an error.

### ISSUE THREAD

**Issue by yellow123Nike** [Visa-Research/volepsi#30]
Hi Professor, I am not very familiar with c++, but I want to implement asynchronous operations, but MC_AWAIT reports an error.
`std::thread th1( [& theirHashes](){MC_AWAIT(chl.recv(theirHashes));});`

**Comment by yellow123Nike** [comment]
<img width="154" alt="image" src="https://user-images.githubusercontent.com/37546857/227185046-9c98f742-08c9-4d84-a8ca-2922998d8e65.png">

**Comment by ladnir** [comment]
That could work if you did

```c++
std::thread th1( [& theirHashes](){ macoro::sync_wait(chl.recv(their Hashes));});
```

But it's quite inefficient to spawn a thread to send one thing.

I'm generally, `MC_AWAIT` can only go inside a `MC_BEGIN`, `MC_END` coroutine block. See https://github.com/Visa-Research/coproto/blob/main/frontend/cpp14Tutorial.cpp

If you have c++ 20 you could also enable that and use the language support for coroutines.

**Comment by ladnir** [comment]
If it's a one off think then you can do the thread thing. Again, I made a long tutorial to inform people how to do this more efficiently. Take a look at it.

**Comment by yellow123Nike** [comment]
thanks
