### ISSUE TITLE
Hi Professor, I am not very familiar with c++, I want to run this project, but there is an error when i run "python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON". I can't solve it.

### ISSUE THREAD

**Issue by GreenEli** [Visa-Research/volepsi#39]
<img src="https://github.com/GreenEli/MiningPool-Attack/blob/master/src/main/webapp/Vole.png?raw=true" >

**Comment by ladnir** [comment]
This appears to be a bug on my side. Let me look into it.

**Comment by RindalVisa** [comment]
not sure, you might need to update your compiler but thats a total guess.
