### ISSUE TITLE
Circuit-PSI with different dataset sizes

### ISSUE THREAD

**Issue by jimouris** [Visa-Research/volepsi#40]
Hi,

I tried modifying [perf.cpp](https://github.com/Visa-Research/volepsi/blob/main/frontend/perf.cpp#L451) to separate `n` to `n_sender` and `n_receiver`. More specifically I changed lines [464](https://github.com/Visa-Research/volepsi/blob/main/frontend/perf.cpp#L464) and [465](https://github.com/Visa-Research/volepsi/blob/main/frontend/perf.cpp#L465) as well as [468](https://github.com/Visa-Research/volepsi/blob/main/frontend/perf.cpp#L468).

It crashes at line [483](https://github.com/Visa-Research/volepsi/blob/main/frontend/perf.cpp#L483) with:
```
terminate called without an active exception
[1]    32658 IOT instruction (core dumped)
````

Is this something that can be supported by the protocol?

**Comment by ladnir** [comment]
This should work but I'm not sure if I properly tested it. Let me look into this.

**Comment by RindalVisa** [comment]
ok, added a test and there was an issue. Pull main and give it a try.

**Comment by jimouris** [comment]
Works now, thanks for looking into this!
