### ISSUE TITLE
arm cmake err

### ISSUE THREAD

**Issue by yellow123Nike** [Visa-Research/volepsi#41]
macoroConfig.cmake : /volepsi/out/install/linux/lib/cmake/macoro/macoroConfig.cmake
CMake Error at /cmake-3.22.0-linux-aarch64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /cmake-3.22.0-linux-aarch64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /cmake-3.22.0-linux-aarch64/share/cmake-3.22/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /volepsi/out/install/linux/lib/cmake/macoro/macoroFindDeps.cmake:71 (find_package)
  /volepsi/out/install/linux/lib/cmake/macoro/macoroConfig.cmake:19 (include)
  /volepsi/out/install/linux/lib/cmake/coproto/coprotoFindDeps.cmake:77 (find_package)
  /volepsi/out/install/linux/lib/cmake/coproto/coprotoFindDeps.cmake:87 (FIND_MACORO)
  /volepsi/out/install/linux/lib/cmake/coproto/coprotoConfig.cmake:15 (include)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:215 (find_package)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:221 (FIND_COPROTO)
  cryptoTools/CMakeLists.txt:154 (include)

-- Configuring incomplete, errors occurred!
See also "/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeOutput.log".
See also "/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeError.log".
CMake Error at thirdparty/fetch.cmake:22 (file):
  file failed to open for reading (No such file or directory):

    /volepsi/thirdparty/log-libOTe.txt
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)

CMake Error at thirdparty/fetch.cmake:23 (message):
  libOTe Configure failed (1).
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)

-- Configuring incomplete, errors occurred!
See also "/volepsi/out/build/linux/CMakeFiles/CMakeOutput.log".
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.

**Comment by yellow123Nike** [comment]
python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON


====== build.py (vole-psi) ========
mkdir -p out/build/linux
cmake -S . -B out/build/linux  -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON -DSUDO_FETCH=OFF -DFETCH_AUTO=ON -DVOLE_PSI_NO_SYSTEM_PATH=true -DPARALLEL_FETCH=64 -DCMAKE_BUILD_TYPE=Release
cmake --build out/build/linux   --parallel 64 
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


warning, setting VOLE_PSI_ENABLE_BOOST as COPROTO_ENABLE_BOOST=ON
warning, setting VOLE_PSI_ENABLE_OPENSSL as COPROTO_ENABLE_OPENSSL=ON
-- vole-psi options
=======================================================
-- Option: VOLE_PSI_NO_SYSTEM_PATH    = true
-- Option: CMAKE_BUILD_TYPE           = Release

-- Option: FETCH_AUTO                 = ON
-- Option: FETCH_SPARSEHASH           = 
-- Option: FETCH_LIBOTE               = 


-- Option: VOLE_PSI_ENABLE_SSE        = ON
-- Option: VOLE_PSI_ENABLE_PIC        = OFF
-- Option: VOLE_PSI_ENABLE_ASAN       = OFF
-- Option: VOLE_PSI_STD_VER           = 17
-- Option: VOLE_PSI_ENABLE_GMW        = ON
-- Option: VOLE_PSI_ENABLE_CPSI       = ON
-- Option: VOLE_PSI_ENABLE_OPPRF      = ON

-- Option: VOLE_PSI_ENABLE_BOOST      = ON
-- Option: VOLE_PSI_ENABLE_OPENSSL    = ON
-- Option: VOLE_PSI_ENABLE_BITPOLYMUL = ON
-- Option: VOLE_PSI_ENABLE_SODIUM     = ON
-- Option: VOLE_PSI_SODIUM_MONTGOMERY = ON
-- Option: VOLE_PSI_ENABLE_RELIC      = OFF
-- VOLEPSI_THIRDPARTY_DIR=/volepsi/out/install/linux
sparsehash-c11 already fetched.
SPARSEHASH_INCLUDE_DIRS=/volepsi/out/install/linux/include



libOTe_options=silentot;silent_vole;circuits;sse;boost;openssl;bitpolymul;no_asan;no_pic;sodium;sodium_montgomery
============= Building libOTe =============
libOTe Checkout 747b4fd3dcbc7618e78dbafdf975a8fb617a6bdd 
'/usr/bin/git' 'checkout' '747b4fd3dcbc7618e78dbafdf975a8fb617a6bdd'
HEAD is now at 747b4fd lib divide fix
libOTe submodule
'/usr/bin/git' 'submodule' 'update' '--recursive'
libOTe Configure
'/cmake-3.22.0-linux-aarch64/bin/cmake' '-S' '/volepsi/out/libOTe' '-B' '/volepsi/out/libOTe/out/build/linux' '-DCMAKE_INSTALL_PREFIX=/usr/local' '-DCMAKE_PREFIX_PATH=/volepsi/out/install/linux;' '-DNO_SYSTEM_PATH=true' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DFETCH_AUTO=ON' '-DVERBOSE_FETCH=ON' '-DENABLE_CIRCUITS=ON' '-DENABLE_MRR=ON' '-DENABLE_IKNP=ON' '-DENABLE_SOFTSPOKEN_OT=ON' '-DENABLE_BITPOLYMUL=ON' '-DENABLE_SILENTOT=ON' '-DENABLE_SILENT_VOLE=ON' '-DENABLE_SSE=ON' '-DENABLE_BOOST=ON' '-DENABLE_OPENSSL=ON' '-DLIBOTE_STD_VER=17' '-DENABLE_PIC=OFF' '-DENABLE_ASAN=OFF' '-DOC_THIRDPARTY_CLONE_DIR=/volepsi/out' '-DOC_THIRDPARTY_INSTALL_PREFIX=/volepsi/out/install/linux' '-DENABLE_SODIUM=ON' '-DENABLE_RELIC=OFF' '-DSODIUM_MONTGOMERY=ON'
-- cryptoTools options
=======================================================
-- Option: CRYPTO_TOOLS_STD_VER  = 17

-- Option: NO_SYSTEM_PATH    = true
-- Option: FETCH_AUTO        = ON
-- Option: VERBOSE_FETCH     = ON

-- Option: FETCH_RELIC       = 
-- Option: FETCH_SODIUM      = 
-- Option: FETCH_BOOST       = 
-- Option: FETCH_COPROTO     = 

-- Option: CMAKE_BUILD_TYPE  = Release
        Release
        Debug
        RelWithDebInfo
-- Option: ENABLE_SPAN_LITE  = ON
-- Option: ENABLE_RELIC      = OFF
-- Option: ENABLE_SODIUM     = ON
-- Option: ENABLE_BOOST      = ON
-- Option: ENABLE_OPENSSL    = ON
-- Option: ENABLE_COPROTO    = true
-- Option: ENABLE_CIRCUITS   = ON
-- Option: ENABLE_SSE        = ON
-- Option: ENABLE_AVX        = ON
-- Option: ENABLE_PIC        = OFF
-- Option: ENABLE_ASAN       = OFF


sodium already fetched.
-- SODIUM_INCLUDE_DIRS:  /volepsi/out/install/linux/include
-- SODIUM_LIBRARIES:  /volepsi/out/install/linux/lib/libsodium.a
-- SODIUM_MONTGOMERY:  ON

macoroConfig.cmake : /volepsi/out/install/linux/lib/cmake/macoro/macoroConfig.cmake
CMake Error at /cmake-3.22.0-linux-aarch64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /cmake-3.22.0-linux-aarch64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /cmake-3.22.0-linux-aarch64/share/cmake-3.22/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /volepsi/out/install/linux/lib/cmake/macoro/macoroFindDeps.cmake:71 (find_package)
  /volepsi/out/install/linux/lib/cmake/macoro/macoroConfig.cmake:19 (include)
  /volepsi/out/install/linux/lib/cmake/coproto/coprotoFindDeps.cmake:77 (find_package)
  /volepsi/out/install/linux/lib/cmake/coproto/coprotoFindDeps.cmake:87 (FIND_MACORO)
  /volepsi/out/install/linux/lib/cmake/coproto/coprotoConfig.cmake:15 (include)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:215 (find_package)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:221 (FIND_COPROTO)
  cryptoTools/CMakeLists.txt:154 (include)


-- Configuring incomplete, errors occurred!
See also "/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeOutput.log".
See also "/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeError.log".
CMake Error at thirdparty/fetch.cmake:22 (file):
  file failed to open for reading (No such file or directory):

    /volepsi/thirdparty/log-libOTe.txt
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)


CMake Error at thirdparty/fetch.cmake:23 (message):
  libOTe Configure failed (1).
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)


-- Configuring incomplete, errors occurred!
See also "/volepsi/out/build/linux/CMakeFiles/CMakeOutput.log".
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.

**Comment by ladnir** [comment]
where are you compiling this? Are you copying the project files between machines?

**Comment by ladnir** [comment]
it seems you first compiled this on x86 and then copied the files onto arm. You then just called build with the existing build artifacts still there. CMake caches some of this stuff and therefore isn't compiling correctly. 

The simplest fix (if the above is true) is to clone the repo to the desired arm machine and do a clean build. Alternatively, you will need to remove all build artifacts from the out folder and then rebuild.

**Comment by yellow123Nike** [comment]
thanks, Has been successfully built

**Comment by VoidR** [comment]
> thanks, Has been successfully built

I encountered the same error as you did and tried deleting the `out` folder, but it still didn't work. Can you please share your solution to this problem?

**Comment by ladnir** [comment]
I'm not sure. I don't have an arm machine.

**Comment by RindalVisa** [comment]
I assume you got it working based on your other issues.

**Comment by Zhangdian825** [comment]
> thanks, Has been successfully built
 Can you please share your solution to this problem?
