### ISSUE TITLE
Hello Professor, can you provide porting for arm64?

### ISSUE THREAD

**Issue by yellow123Nike** [Visa-Research/volepsi#43]
Hello Professor, can you provide porting for arm64?
I tried to compile but got stuck on the avx directive
<img width="405" alt="image" src="https://github.com/Visa-Research/volepsi/assets/37546857/9cdfc089-f731-4812-b5eb-895b6469b7f4">

**Comment by ladnir** [comment]
yeah, for now, you should just be able to comment that line out.

**Comment by yellow123Nike** [comment]
thanks, Has been successfully built

**Comment by RindalVisa** [comment]
should be resolved in master. Thanks for opening the issue
