### ISSUE TITLE
error when building variant-lite

### ISSUE THREAD

**Issue by Bruce-Luuuu** [Visa-Research/volepsi#45]
The outputs are as follows:

![B8ZGC3C~31ZJ8_EVB3{SRMC](https://github.com/Visa-Research/volepsi/assets/75268603/badbe8cb-3475-4133-95a9-e558d4442d8a)
![VW1%O2_G%4MOO1W3%EKCFXV](https://github.com/Visa-Research/volepsi/assets/75268603/3b452cee-6f57-492b-9f1c-3fbe531c32e2)
![C} ZAS@}{_1W(THF U5DTK7](https://github.com/Visa-Research/volepsi/assets/75268603/f92f1a8c-5232-452f-b6d0-cac208ff0982)

**Comment by ladnir** [comment]
I'll investigate. Thanks.

**Comment by Bruce-Luuuu** [comment]
As my issue is similar to [issue 32](https://github.com/Visa-Research/volepsi/issues/32), I leave a comment there asking how he fixed it. But I didn't got '-std=c++17' and my gcc version is 12.2.0.

Later I read [issue93](https://github.com/osu-crypto/libOTe/issues/93) and I think maybe the reason I got the error log is because I installed libsodium on my own. So I follow your advice. But I still got exactly the same error log as above.

**Comment by ladnir** [comment]
I don't think it's related to those... 

My guess is that the when_all_ready header need to #include <utility>

Can you try that?

**Comment by Bruce-Luuuu** [comment]
Sorry, could you be more specific? Thanks.

**Comment by ladnir** [comment]
So you see the file that the compiler is saying that `std::exchange` doesn't exist? `macoro/when_all.h`

Add `#include <utility>` to the top and try to compile

**Comment by Bruce-Luuuu** [comment]
Thanks for your help. 
I succeeded in building variant-lite following your guide, and then I encountered a similar error log which says ```std::exchange``` doesn't exist several times. Each time I add ```#include <utility>``` at the top of the corresponding file.
Now I build the whole project successfully.
: )

**Comment by ladnir** [comment]
First of all variant wasn't the issue. Macoro was.

Can you remember where these other errors were? I need to fix them. Unfortunately I don't get these errors on my machine so need your belp

Thanks

**Comment by Bruce-Luuuu** [comment]
![1VWMVZY IYH9A{AI6LCN%ED](https://github.com/Visa-Research/volepsi/assets/75268603/7ab4a4d8-6446-4fb5-9a1d-0cedcec3a401)

![6QB3QBKF3 `S %LHTK{IE I](https://github.com/Visa-Research/volepsi/assets/75268603/dfdc2fcb-2433-4ee1-9a81-0102b48e47ba)

![WY86%16VARIO(W_OF1IFT(2](https://github.com/Visa-Research/volepsi/assets/75268603/b749f254-e9bc-4586-bad5-c1f844d6a8c0)

**Comment by ladnir** [comment]
Much appreciated. I'll send out a fix soon.
