### ISSUE TITLE
Errors in build

### ISSUE THREAD

**Issue by enidastronomical** [Visa-Research/volepsi#46]
Hello professor, sorry to disturb you. I run the build command on my macbook, and an error happens. I tried to switch to another previous version of volepsi, but the same error appeared again.
The error information is as follows.

------------------------------------------------------------------------------------------------

[100%] Linking CXX executable frontend_libOTe
Undefined symbols for architecture x86_64:
  "coproto::internal::SockScheduler::initLocalSlot(coproto::SessionID const&, coproto::internal::ExecutorRef const&, std::__1::unique_lock<std::__1::mutex>&)", referenced from:
      void coproto::internal::SockScheduler::init<coproto::LocalAsyncSocket::Sock>(coproto::LocalAsyncSocket::Sock*, coproto::SessionID) in main.cpp.o
      void coproto::internal::SockScheduler::init<coproto::detail::AsioSocket<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::any_io_executor> >::Sock>(coproto::detail::AsioSocket<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::any_io_executor> >::Sock*, coproto::SessionID) in main.cpp.o
      void coproto::internal::SockScheduler::init<coproto::BufferingSocket::SockImpl>(coproto::BufferingSocket::SockImpl*, coproto::SessionID) in main.cpp.o
      void coproto::internal::SockScheduler::init<coproto::LocalAsyncSocket::Sock>(coproto::LocalAsyncSocket::Sock*, coproto::SessionID) in liblibOTe_Tests.a(SilentOT_Tests.cpp.o)
      void coproto::internal::SockScheduler::init<coproto::LocalAsyncSocket::Sock>(coproto::LocalAsyncSocket::Sock*, coproto::SessionID) in liblibOTe_Tests.a(Vole_Tests.cpp.o)
      void coproto::internal::SockScheduler::init<coproto::BufferingSocket::SockImpl>(coproto::BufferingSocket::SockImpl*, coproto::SessionID) in liblibOTe_Tests.a(Vole_Tests.cpp.o)
      void coproto::internal::SockScheduler::init<coproto::LocalAsyncSocket::Sock>(coproto::LocalAsyncSocket::Sock*, coproto::SessionID) in liblibOTe_Tests.a(OT_Tests.cpp.o)
      ...
  "coproto::internal::SockScheduler::send(coproto::SessionID, coproto::internal::SendBuffer&&, macoro::coroutine_handle<void>, macoro::stop_token&&, bool)", referenced from:
      auto macoro::await_suspend<coproto::internal::MoveSendProto<char>, macoro::detail::blocking_promise<void> >(coproto::internal::MoveSendProto<char>&, macoro::coroutine_handle<macoro::detail::blocking_promise<void> >, std::__1::enable_if<(!(has_void_await_suspend<coproto::internal::MoveSendProto<char>&, std::__1>::value)) && (!(has_bool_await_suspend<coproto::internal::MoveSendProto<char>&, std::__1>::value)), macoro::empty_state>::type) in main.cpp.o
      macoro::coroutine_handle<void> coproto::internal::MoveSendProto<std::__1::vector<osuCrypto::FeistelRistPopf::PopfFunc, std::__1::allocator<osuCrypto::FeistelRistPopf::PopfFunc> > >::await_suspend<macoro::coroutine_handle<macoro::detail::task_promise<void, true> > >(macoro::coroutine_handle<macoro::detail::task_promise<void, true> > const&) in main.cpp.o
      macoro::coroutine_handle<void> coproto::internal::MoveSendProto<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >::await_suspend<macoro::coroutine_handle<macoro::detail::task_promise<void, true> > >(macoro::coroutine_handle<macoro::detail::task_promise<void, true> > const&) in main.cpp.o
      macoro::coroutine_handle<void> coproto::internal::MoveSendProto<std::__1::vector<osuCrypto::FeistelMulRistPopf::PopfFunc, std::__1::allocator<osuCrypto::FeistelMulRistPopf::PopfFunc> > >::await_suspend<macoro::coroutine_handle<macoro::detail::task_promise<void, true> > >(macoro::coroutine_handle<macoro::detail::task_promise<void, true> > const&) in main.cpp.o
      auto macoro::await_suspend<coproto::internal::RefSendProto<unsigned char>, macoro::detail::task_promise<void, true> >(coproto::internal::RefSendProto<unsigned char>&, macoro::coroutine_handle<macoro::detail::task_promise<void, true> >, std::__1::enable_if<(!(has_void_await_suspend<coproto::internal::RefSendProto<unsigned char>&, std::__1>::value)) && (!(has_bool_await_suspend<coproto::internal::RefSendProto<unsigned char>&, std::__1>::value)), macoro::empty_state>::type) in util.cpp.o
      auto macoro::await_suspend<coproto::internal::MoveSendProto<unsigned char>, macoro::detail::task_promise<void, true> >(coproto::internal::MoveSendProto<unsigned char>&, macoro::coroutine_handle<macoro::detail::task_promise<void, true> >, std::__1::enable_if<(!(has_void_await_suspend<coproto::internal::MoveSendProto<unsigned char>&, std::__1>::value)) && (!(has_bool_await_suspend<coproto::internal::MoveSendProto<unsigned char>&, std::__1>::value)), macoro::empty_state>::type) in util.cpp.o
      macoro::coroutine_handle<void> coproto::internal::MoveSendProto<std::__1::vector<osuCrypto::FeistelRistPopf::PopfFunc, std::__1::allocator<osuCrypto::FeistelRistPopf::PopfFunc> > >::await_suspend<macoro::coroutine_handle<macoro::detail::task_promise<void, true> > >(macoro::coroutine_handle<macoro::detail::task_promise<void, true> > const&) in liblibOTe.a(OTExtInterface.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [frontend/frontend_libOTe] Error 1
make[1]: *** [frontend/CMakeFiles/frontend_libOTe.dir/all] Error 2
make: *** [all] Error 2
CMake Error at thirdparty/fetch.cmake:22 (file):
  file failed to open for reading (No such file or directory):

    /Users/yc/vvolepsi/thirdparty/log-libOTe.txt
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:63 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)

CMake Error at thirdparty/fetch.cmake:23 (message):
  libOTe Build failed (2).
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:63 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)

-- Configuring incomplete, errors occurred!
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.

**Comment by enidastronomical** [comment]
I tried the instructions in issue 44, but it still doesn't work.

**Comment by ladnir** [comment]
Are you on Mac m1?
