### ISSUE TITLE
How do I run this program?

### ISSUE THREAD

**Issue by yangchunmian123** [Visa-Research/volepsi#47]
Hi Professor, I am having some problems reproducing this program as described below:
First, I can build the whole program. Here are the parameter settings :

![image](https://github.com/Visa-Research/volepsi/assets/118784421/bd86f357-312c-49fd-b69c-619433c6a6d3)

Then I can also pass all the unit tests. like this：

![image](https://github.com/Visa-Research/volepsi/assets/118784421/7027ba7e-0898-454f-98a6-e0758f52b7af)

But at the moment I can only run the -u command and the -perf command. All other commands print out usage information. I've tried several commands to run the PSI protocol, but they always output usage information without actually running the PSI protocol. I'm not very proficient with the code and I can't find out what the problem is, I wonder if the professor can give a set of running examples so that I can determine what's wrong.

**Comment by ladnir** [comment]
What do you want to run?

**Comment by yangchunmian123** [comment]
Hello Professor, I've gradually learned how to run it and I don't have any more questions to ask for the time being, sorry for forgetting to close the dialog in time.
