### ISSUE TITLE
segmentation fault occurred when executing frontend -net

### ISSUE THREAD

**Issue by stone-wlg** [Visa-Research/volepsi#5]
Env:
- MacOS 13.0

Steps:
- ./frontend -net -sender -r 0 -server 0
- ./frontend -net -recver -r 1 -server 1

Result:
- [1]    3254 segmentation fault  ./frontend -net -recver -r 1 -server 1

**Comment by ladnir** [comment]
do the unit test pass?

**Comment by stone-wlg** [comment]
sorry, it is my fault, i mis-understand arg server
- ./frontend -net -sender -r 0 -server 1
- ./frontend -net -recver -r 1 -server 0

it workds
