### ISSUE TITLE
aarch64 cmake error

### ISSUE THREAD

**Issue by Zhangdian825** [Visa-Research/volepsi#51]
**# lscpu**
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       0x48
Model:                           0
Stepping:                        0x1
CPU max MHz:                     2600.0000
CPU min MHz:                     2600.0000
BogoMIPS:                        200.00
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
**build parames:
python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON -DVOLE_PSI_ENABLE_BITPOLYMUL=false -DVOLE_PSI_ENABLE_SSE=false -DVOLE_PSI_ENABLE_GMW=false -DVOLE_PSI_ENABLE_CPSI=false**
boost has been successfully built:
**/home/vole# ll /home/vole/volepsi/out/install/linux/lib/** 
total 6768
drwxr-xr-x  4 root root    4096 Oct 19 09:58 ./
drwxr-xr-x  4 root root      68 Oct 19 09:53 ../
drwxr-xr-x 17 root root    4096 Oct 19 09:58 cmake/
-rw-r--r--  1 root root    9864 Oct 19 09:55 libboost_atomic.a
lrwxrwxrwx  1 root root      25 Oct 19 09:55 libboost_atomic.so -> libboost_atomic.so.1.77.0*
-rwxr-xr-x  1 root root   18800 Oct 19 09:55 libboost_atomic.so.1.77.0*
-rw-r--r--  1 root root    1506 Oct 19 09:55 libboost_date_time.a
lrwxrwxrwx  1 root root      28 Oct 19 09:55 libboost_date_time.so -> libboost_date_time.so.1.77.0*
-rwxr-xr-x  1 root root    7984 Oct 19 09:55 libboost_date_time.so.1.77.0*
-rw-r--r--  1 root root  553590 Oct 19 09:55 libboost_filesystem.a
lrwxrwxrwx  1 root root      29 Oct 19 09:55 libboost_filesystem.so -> libboost_filesystem.so.1.77.0*
-rwxr-xr-x  1 root root  161432 Oct 19 09:55 libboost_filesystem.so.1.77.0*
-rw-r--r--  1 root root  746128 Oct 19 09:55 libboost_regex.a
lrwxrwxrwx  1 root root      24 Oct 19 09:55 libboost_regex.so -> libboost_regex.so.1.77.0*
-rwxr-xr-x  1 root root  351872 Oct 19 09:55 libboost_regex.so.1.77.0*
-rw-r--r--  1 root root    1484 Oct 19 09:55 libboost_system.a
lrwxrwxrwx  1 root root      25 Oct 19 09:55 libboost_system.so -> libboost_system.so.1.77.0*
-rwxr-xr-x  1 root root    7968 Oct 19 09:55 libboost_system.so.1.77.0*
-rw-r--r--  1 root root  352246 Oct 19 09:55 libboost_thread.a
lrwxrwxrwx  1 root root      25 Oct 19 09:55 libboost_thread.so -> libboost_thread.so.1.77.0*
-rwxr-xr-x  1 root root  154680 Oct 19 09:55 libboost_thread.so.1.77.0*
-rw-r--r--  1 root root  276880 Oct 19 09:56 libcoproto.a
-rw-r--r--  1 root root   28790 Oct 19 09:52 libmacoro.a
-rw-r--r--  1 root root 2662870 Oct 19 09:52 libsodium.a
-rwxr-xr-x  1 root root     994 Oct 19 09:52 libsodium.la*
lrwxrwxrwx  1 root root      19 Oct 19 09:52 libsodium.so -> libsodium.so.27.0.0*
lrwxrwxrwx  1 root root      19 Oct 19 09:52 libsodium.so.27 -> libsodium.so.27.0.0*
-rwxr-xr-x  1 root root 1551936 Oct 19 09:52 libsodium.so.27.0.0*
drwxr-xr-x  2 root root      26 Oct 19 09:52 pkgconfig/

**/home/vole/volepsi# python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON -DVOLE_PSI_ENABLE_BITPOLYMUL=false -DVOLE_PSI_ENABLE_SSE=false -DVOLE_PSI_ENABLE_GMW=false -DVOLE_PSI_ENABLE_CPSI=false**

====== build.py (vole-psi) ========
mkdir -p out/build/linux
cmake -S . -B out/build/linux  -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON -DVOLE_PSI_ENABLE_BITPOLYMUL=false -DVOLE_PSI_ENABLE_SSE=false -DVOLE_PSI_ENABLE_GMW=false -DVOLE_PSI_ENABLE_CPSI=false -DSUDO_FETCH=OFF -DFETCH_AUTO=ON -DVOLE_PSI_NO_SYSTEM_PATH=true -DPARALLEL_FETCH=4 -DCMAKE_BUILD_TYPE=Release
cmake --build out/build/linux   --parallel 4 
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

warning, setting VOLE_PSI_ENABLE_BOOST as COPROTO_ENABLE_BOOST=ON
warning, setting VOLE_PSI_ENABLE_OPENSSL as COPROTO_ENABLE_OPENSSL=ON
-- vole-psi options
=======================================================
-- Option: VOLE_PSI_NO_SYSTEM_PATH    = true
-- Option: CMAKE_BUILD_TYPE           = Release

-- Option: FETCH_AUTO                 = ON
-- Option: FETCH_SPARSEHASH           = 
-- Option: FETCH_LIBOTE               = 

-- Option: VOLE_PSI_ENABLE_SSE        = false
-- Option: VOLE_PSI_ENABLE_PIC        = OFF
-- Option: VOLE_PSI_ENABLE_ASAN       = OFF
-- Option: VOLE_PSI_STD_VER           = 17
-- Option: VOLE_PSI_ENABLE_GMW        = false
-- Option: VOLE_PSI_ENABLE_CPSI       = false
-- Option: VOLE_PSI_ENABLE_OPPRF      = ON

-- Option: VOLE_PSI_ENABLE_BOOST      = ON
-- Option: VOLE_PSI_ENABLE_OPENSSL    = ON
-- Option: VOLE_PSI_ENABLE_BITPOLYMUL = false
-- Option: VOLE_PSI_ENABLE_SODIUM     = ON
-- Option: VOLE_PSI_SODIUM_MONTGOMERY = ON
-- Option: VOLE_PSI_ENABLE_RELIC      = OFF
-- VOLEPSI_THIRDPARTY_DIR=/home/vole/volepsi/out/install/linux
sparsehash-c11 already fetched.
SPARSEHASH_INCLUDE_DIRS=/home/vole/volepsi/out/install/linux/include

libOTe_options=silentot;silent_vole;circuits;no_sse;boost;openssl;no_asan;no_pic;sodium;sodium_montgomery
============= Building libOTe =============
libOTe Checkout 747b4fd3dcbc7618e78dbafdf975a8fb617a6bdd 
'/usr/bin/git' 'checkout' '747b4fd3dcbc7618e78dbafdf975a8fb617a6bdd'
HEAD is now at 747b4fd lib divide fix
libOTe submodule
'/usr/bin/git' 'submodule' 'update' '--recursive'
libOTe Configure
'/usr/local/bin/cmake' '-S' '/home/vole/volepsi/out/libOTe' '-B' '/home/vole/volepsi/out/libOTe/out/build/linux' '-DCMAKE_INSTALL_PREFIX=/usr/local' '-DCMAKE_PREFIX_PATH=/home/vole/volepsi/out/install/linux;' '-DNO_SYSTEM_PATH=true' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DFETCH_AUTO=ON' '-DVERBOSE_FETCH=ON' '-DENABLE_CIRCUITS=ON' '-DENABLE_MRR=ON' '-DENABLE_IKNP=ON' '-DENABLE_SOFTSPOKEN_OT=ON' '-DENABLE_BITPOLYMUL=false' '-DENABLE_SILENTOT=ON' '-DENABLE_SILENT_VOLE=ON' '-DENABLE_SSE=false' '-DENABLE_BOOST=ON' '-DENABLE_OPENSSL=ON' '-DLIBOTE_STD_VER=17' '-DENABLE_PIC=OFF' '-DENABLE_ASAN=OFF' '-DOC_THIRDPARTY_CLONE_DIR=/home/vole/volepsi/out' '-DOC_THIRDPARTY_INSTALL_PREFIX=/home/vole/volepsi/out/install/linux' '-DENABLE_SODIUM=ON' '-DENABLE_RELIC=OFF' '-DSODIUM_MONTGOMERY=ON'
AVX requires SSE to be enabled.
-- cryptoTools options
=======================================================
-- Option: CRYPTO_TOOLS_STD_VER  = 17

-- Option: NO_SYSTEM_PATH    = true
-- Option: FETCH_AUTO        = ON
-- Option: VERBOSE_FETCH     = ON

-- Option: FETCH_RELIC       = 
-- Option: FETCH_SODIUM      = 
-- Option: FETCH_BOOST       = 
-- Option: FETCH_COPROTO     = 

-- Option: CMAKE_BUILD_TYPE  = Release
	Release
	Debug
	RelWithDebInfo
-- Option: ENABLE_SPAN_LITE  = ON
-- Option: ENABLE_RELIC      = OFF
-- Option: ENABLE_SODIUM     = ON
-- Option: ENABLE_BOOST      = ON
-- Option: ENABLE_OPENSSL    = ON
-- Option: ENABLE_COPROTO    = true
-- Option: ENABLE_CIRCUITS   = ON
-- Option: ENABLE_SSE        = false
-- Option: ENABLE_AVX        = OFF
-- Option: ENABLE_PIC        = OFF
-- Option: ENABLE_ASAN       = OFF

sodium already fetched.
-- SODIUM_INCLUDE_DIRS:  /home/vole/volepsi/out/install/linux/include
-- SODIUM_LIBRARIES:  /home/vole/volepsi/out/install/linux/lib/libsodium.a
-- SODIUM_MONTGOMERY:  ON

macoroConfig.cmake : /home/vole/volepsi/out/install/linux/lib/cmake/macoro/macoroConfig.cmake
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.20/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/vole/volepsi/out/install/linux/lib/cmake/macoro/macoroFindDeps.cmake:71 (find_package)
  /home/vole/volepsi/out/install/linux/lib/cmake/macoro/macoroConfig.cmake:19 (include)
  /home/vole/volepsi/out/install/linux/lib/cmake/coproto/coprotoFindDeps.cmake:77 (find_package)
  /home/vole/volepsi/out/install/linux/lib/cmake/coproto/coprotoFindDeps.cmake:87 (FIND_MACORO)
  /home/vole/volepsi/out/install/linux/lib/cmake/coproto/coprotoConfig.cmake:15 (include)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:215 (find_package)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:221 (FIND_COPROTO)
  cryptoTools/CMakeLists.txt:154 (include)

-- Configuring incomplete, errors occurred!
See also "/home/vole/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeOutput.log".
See also "/home/vole/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeError.log".
CMake Error at thirdparty/fetch.cmake:22 (file):
  file failed to open for reading (No such file or directory):

    /home/vole/volepsi/thirdparty/log-libOTe.txt
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)

CMake Error at thirdparty/fetch.cmake:23 (message):
  libOTe Configure failed (1).
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)

-- Configuring incomplete, errors occurred!
See also "/home/vole/volepsi/out/build/linux/CMakeFiles/CMakeOutput.log".
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.

**Comment by ladnir** [comment]
try this? https://github.com/alicevision/geogram/issues/2

**Comment by Zhangdian825** [comment]
> try this? [alicevision/geogram#2](https://github.com/alicevision/geogram/issues/2)

Thanks,Has been successfully built
1.Solved it by including this in the ./out/libOTe/cryptoTools/CMakeLists.txt
set(CMAKE_THREAD_LIBS_INIT "pthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
2.set(COMMON_FLAGS "-Wall -march=x86-64 -Wfatal-errors")->>>set(COMMON_FLAGS "-Wall -march=armv8-a -Wfatal-errors")
