### ISSUE TITLE
PaXoS test

### ISSUE THREAD

**Issue by LiZeKunJava** [Visa-Research/volepsi#52]
Hi Professor, I would like to ask how to output the intersection result of -perf -paxos test. How do I enter my own dataset file to invoke paxos algorithm.

**Comment by ladnir** [comment]
`-perf` means its a performance benchmark. Not intended for actual use.

You can see the unit tests for how to use it. https://github.com/Visa-Research/volepsi/blob/main/tests/Paxos_Tests.cpp#L601

**Comment by LiZeKunJava** [comment]
Thank you very much
