### ISSUE TITLE
Question about PSI

### ISSUE THREAD

**Issue by LiZeKunJava** [Visa-Research/volepsi#54]
Hello, Professor.I noticed that OPPRF is used in PSI mode for file input. May I ask where subfield-VOLE is used? I can't find it.Hello, Professor.

**Comment by ladnir** [comment]
So the performance numbers in the paper were obtained via some hacking. A working version was never completed. There is however an active PR for libOTe that will enable this. https://github.com/osu-crypto/libOTe/pull/127

Once completed it will be easy to add it to this library

**Comment by jsuper** [comment]
Hello Professor, I noticed that the OT PR based on subfield-VOLE has now been merged into the libOTE library. May I ask how the high-performance version of PSI using subfield-VOLE is currently implemented, or is it already in the process of being implemented? Is there a corresponding timeline for this?

**Comment by ladnir** [comment]
Oh, good point, kinda forgot about that. Don't currently have plans but would be pretty easy to implement now.

**Comment by ladnir** [comment]
see https://github.com/Visa-Research/volepsi/issues/73
