### ISSUE TITLE
build err on Macos

### ISSUE THREAD

**Issue by WandQ** [Visa-Research/volepsi#55]
python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON -DVOLE_PSI_ENABLE_RELIC=OFF -DVOLE_PSI_ENABLE_SODIUM=ON -DVOLE_PSI_ENABLE_SSE=OFF -DFETCH_ALL=ON

....
/Users/admin/code/volepsi/volePSI/PaxosImpl.h:1144:52: fatal error: use of undeclared identifier '_MM_HINT_T0'
                                                                _mm_prefetch((const char*)&mCols[colIdx2], _MM_HINT_T0);
                                                                                                           ^
1 error generated.
make[2]: *** [volePSI/CMakeFiles/volePSI.dir/RsCpsi.cpp.o] Error 1
make[1]: *** [volePSI/CMakeFiles/volePSI.dir/all] Error 2
make: *** [all] Error 2

**Comment by WandQ** [comment]
Can I delete the code from line 1142 to line 1145 in the file PaxosImpl.h to solve the problem? Or is there any alternative solution? Here is the code:
`if (node.mWeight == 1)
{
_mm_prefetch((const char*)&mCols[colIdx2], _MM_HINT_T0);
}`

**Comment by ladnir** [comment]
You can delete and I'll fix this

**Comment by ladnir** [comment]
That is correct
