### ISSUE TITLE
Question about PSI ID data type 

### ISSUE THREAD

**Issue by jsuper** [Visa-Research/volepsi#56]
Hello professor!

I found the PSI only accept id which data type is unsigned int 64(uint64_t), If the ID type is string (e.g sha256 hash value of phone number). How can i convert it to u64 ? Do algorithms need to be modified?

Thanks very much!

@ladnir

**Comment by ladnir** [comment]
It take block as input. Not u64. block is 128 bit. For Semi-honest that should be big enough. For malicious, you can choose a random seed/salt and rehash to 128 bit block.

**Comment by jsuper** [comment]
> It take block as input. Not u64. block is 128 bit. For Semi-honest that should be big enough. For malicious, you can choose a random seed/salt and rehash to 128 bit block.

OK, thanks professor
