### ISSUE TITLE
Does the frontend have a function to display communication cost?

### ISSUE THREAD

**Issue by 1228902681** [Visa-Research/volepsi#6]
Hello, I run your code. It showed the running time. I want to see its communication cost. Can you tell me how you tested it?

**Comment by ladnir** [comment]
Some do. For example https://github.com/Visa-Research/volepsi/blob/eb788bb250d9be4648ef057e90adf89125e01fd5/frontend/perf.cpp#L440

You could add this print to the others.

**Comment by 1228902681** [comment]
OK，thanks for your help.
