### ISSUE TITLE
what is the difference between `davies-meyer F` and `avies-meyer-Oseas F` ?

### ISSUE THREAD

**Issue by qxzhou1010** [Visa-Research/volepsi#60]
In this line https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOprf.cpp#L451C22-L451C22 and https://github.com/Visa-Research/volepsi/blob/main/volePSI/RsOprf.cpp#L490C25-L490C44.

Here using different instances of  `H(u)`. In malicious version, the `H(u)` is:
```
// compute davies-meyer F
//    F(x) = H( Decode(x, a) + w, x)
// where 
//    H(u,v) = AES_u(v) ^ v

```

Howerver, in semi-honest version, the `H(u)` is:

```
// compute davies-meyer-Oseas F
//      F(x) = H(Decode(x, a))
// where
//      H(u) = AES_fixed(u) ^ u
oc::mAesFixedKey.hashBlocks(outputs, outputs);
```

What is the difference between the two cases?  What is the reason for using different `H(u)` in malicious and semi-honest cases?

**Comment by ladnir** [comment]
Has to due with the requirements of sh vs malicious. In sh the adversary is not adaptive, ie they I'll follow the protocol. As such, it's sufficient to do a simple hash. In malicious, the adversary might cheat. This can bias the output distribution slightly. We prevent this by randomizing the hash with a salt.
