### ISSUE TITLE
How can I use my boost that have installed in my computer and not download a new one?

### ISSUE THREAD

**Issue by Fix3dP0int** [Visa-Research/volepsi#62]
as the title suggests, please give me some solutions. Thank you very much!

**Comment by ladnir** [comment]
Are you willing to modify the code?

If so, do a clean clone without boost enabled. Then go to out/coproto/cmake/coprotoFindDeps.cmake

Go to line https://github.com/Visa-Research/coproto/blob/main/cmake/coprotoFindDeps.cmake#L146

And set the version of boost you want or remove the versioning altogether.

To be sure it doesn't fetch if it doesn't find your boost, you can comment out

https://github.com/Visa-Research/coproto/blob/main/cmake/coprotoFindDeps.cmake#L155

I think that should do it. Maybe I could add better support for this. Will think about it...
