### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by friendsAI** [Visa-Research/volepsi#65]
when I execute the command: python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON, error occurs. The following are error messages:

-- Configuring incomplete, errors occurred!
CMake Error at thirdparty/fetch.cmake:22 (file):
 file failed to open for reading (No such file or directory):
 /home/susan/VOLEpsi/volepsi/thirdparty/log-libOTe.txt
Call Stack (most recent call first):
thirdparty/getLibOTe.cmake:62 (run)
cmake/findDependancies.cmake:115 (include)
CMakeLists.txt:14 (include)
CMake Error at thirdparty/fetch.cmake:23 (message):
libOTe Configure failed (1).
Call Stack (most recent call first):
thirdparty/getLibOTe.cmake:62 (run)
cmake/findDependancies.cmake:115 (include)
CMakeLists.txt:14 (include)
-- Configuring incomplete, errors occurred!
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.

The OS version：Ubuntu 22.04

**Comment by friendsAI** [comment]
resloved.

**Comment by zzzhhhlll** [comment]
> when I execute the command: python3 build.py -DVOLE_PSI_ENABLE_BOOST=ON, error occurs. The following are error messages:
> 
> -- Configuring incomplete, errors occurred! CMake Error at thirdparty/fetch.cmake:22 (file): file failed to open for reading (No such file or directory): /home/susan/VOLEpsi/volepsi/thirdparty/log-libOTe.txt Call Stack (most recent call first): thirdparty/getLibOTe.cmake:62 (run) cmake/findDependancies.cmake:115 (include) CMakeLists.txt:14 (include) CMake Error at thirdparty/fetch.cmake:23 (message): libOTe Configure failed (1). Call Stack (most recent call first): thirdparty/getLibOTe.cmake:62 (run) cmake/findDependancies.cmake:115 (include) CMakeLists.txt:14 (include) -- Configuring incomplete, errors occurred! gmake: Makefile: No such file or directory gmake: *** No rule to make target 'Makefile'. Stop.
> 
> The OS version：Ubuntu 22.04

I seem to have the same problem as you. How did you solve it? Thank you

**Comment by ladnir** [comment]
Please share the full error message

**Comment by seven7-qiqi** [comment]
> Please share the full error message

The following is error message:"
CMake Error at cryptoTools/thirdparty/fetch.cmake:21 (message):
  Configure failed (1).
Call Stack (most recent call first):
  cryptoTools/thirdparty/getSodium.cmake:76 (run)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:143 (include)
  cryptoTools/CMakeLists.txt:46 (include)


-- Configuring incomplete, errors occurred!
CMake Error at thirdparty/fetch.cmake:22 (file):
  file failed to open for reading (No such file or directory):

    /home/cc/my file/volepsi/thirdparty/log-libOTe.txt
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)


CMake Error at thirdparty/fetch.cmake:23 (message):
  libOTe Configure failed (1).
Call Stack (most recent call first):
  thirdparty/getLibOTe.cmake:62 (run)
  cmake/findDependancies.cmake:115 (include)
  CMakeLists.txt:14 (include)


-- Configuring incomplete, errors occurred!
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.
"

I got the above error when running on different versions.
version1:Unbuntu 24.04(g++13 gcc 13)
version1:Unbuntu 20.04(g++11 gcc 11)

Hope to get a reply as soon as possible, thank you!
