### ISSUE TITLE
Question about OKVS in RR22

### ISSUE THREAD

**Issue by lzjluzijie** [Visa-Research/volepsi#66]
Hi, I am learning OKVS and I want to use the OKVS in RR22, since it seems to be state-of-the-art. But I only find "paxos" implementations in this repo (https://github.com/Visa-Research/volepsi/blob/main/tests/Paxos_Tests.cpp). Could you give me some guidance? Thank you.

**Comment by ladnir** [comment]
this is in fact RR22. Baxos is the binned version. The naming is just a bit off...

**Comment by lzjluzijie** [comment]
I see, thank you!

**Comment by ladnir** [comment]
FYI, there are better okvs schemes. You can Google ribbon filter. I was able to get 1.01 expansion in an experiment. There are some papers discussing this for psi but can't remember which.

**Comment by ladnir** [comment]
Improved CRL compression with structured linear functions @rwc2022

**Comment by ladnir** [comment]
please close your issue if its resolved.

**Comment by lzjluzijie** [comment]
Thank you, this is very helpful 😄
