### ISSUE TITLE
Errors encountered when using paxos to implement OPRF for Low communication in RR22

### ISSUE THREAD

**Issue by liuwenxin98** [Visa-Research/volepsi#72]
Hi, 

The problem is described below:
When I have a set of data：
```
span<block> key = ...;
span<uint64_t> val = ...;
auto paxos = Paxos<uint32_t>{};
paxos.init(key.size(), 3, mSsp, PaxosParam::GF128, seed);
```
When I use paxos to get the paxos structure:
```
paxos.setInput(key);
paxos.encode<uint64_t>(val, p, nullptr);
```
I encountered the exception "std::runtime_error("the gf128 dense encoding is only implemented for osuCrypto::block type"), which seems to originate from the part of the encode that requires the use the dense part i.e. g>0 to call the multAdd interface from Pxutil.h.
Is this problem solvable?

**Comment by qxzhou1010** [comment]
Hi, I am encountering the same problem as you. Changing `PaxosParam::GF128` in `paxos.init(key.size(), 3, mSsp, PaxosParam::GF128, seed);` to `PaxosParam::Binary` might fix the issue.  So, if we need an `u64` okvs's encode output, we can only use the `Binary` dense type.

However, I am not sure about the difference between GF128 and Binary. If you know, please let me know. Thanks.

**Comment by liuwenxin98** [comment]
> Hi, I am encountering the same problem as you. Changing `PaxosParam::GF128` in `paxos.init(key.size(), 3, mSsp, PaxosParam::GF128, seed);` to `PaxosParam::Binary` might fix the issue. So, if we need an `u64` okvs's encode output, we can only use the `Binary` dense type.
> 
> However, I am not sure about the difference between GF128 and Binary. If you know, please let me know. Thanks.

I'm also using PaxosParam::Binary for the time being to solve this problem, the difference between them can be found in [RR22] https://eprint.iacr.org/2022/320.pdf. On pages 8-9 of the paper there is a mention of the two forms for guaranteeing full rank of matrices and their possible performance gaps

**Comment by ladnir** [comment]
it tells you the issue, you can only use `PaxosParam::GF128` if the type being encoded is `block`. Use `binary` if not. you can read the paper is you want to understand why.

**Comment by liuwenxin98** [comment]
Thank you very much for your reply. I've adjusted it to `binary` and have no further problems
