### ISSUE TITLE
How to construct the matrix H in "Blazing Fast PSI from Improved OKVS and Subfield VOLE"

### ISSUE THREAD

**Issue by miraitowa** [Visa-Research/volepsi#77]
Professor, hello, how are the sparse matrix and dense matrix in the matrix H in the paper "Blazing Fast PSI from Improved OKVS and Subfield VOLE" constructed? Why is it constructed in this way? Is there any advantage? Does the previous paper mention the advantages of this construction? If so, please provide the corresponding literature, thank you!

**Comment by ladnir** [comment]
Each row of the sparse part is a random vector with w=3 ones.

The dense part is a bit more complicated. But for binary it's just purely random.

The sparse part is more efficient but can fail to be invertible / encodable. The dense part fixes up any issues in the sparse part. The dense part is invertible with very high probability.

Sparse = maybe not invertible but effecient
Dense = invertible but not efficient
