### ISSUE TITLE
An error occurred while building

### ISSUE THREAD

**Issue by WandQ** [Visa-Research/volepsi#9]
Hi，
The error is reported as follows：
root@606ba53156e9:~/volepsi# python3 build.py -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON

====== build.py (vole-psi) ========
mkdir -p out/build/linux
cmake -S . -B out/build/linux  -DCOPROTO_ENABLE_BOOST=ON -DCOPROTO_ENABLE_OPENSSL=ON -DSUDO_FETCH=OFF -DFETCH_AUTO=ON -DPARALLEL_FETCH=4 -DCMAKE_BUILD_TYPE=Release
cmake --build out/build/linux   --parallel 4
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

-- vole-psi options
=======================================================
-- Option: FETCH_AUTO        = ON
-- Option: FETCH_SPARSEHASH  =
-- Option: FETCH_LIBOTE      =
-- Option: FETCH_LIBDIVIDE   =
-- Option: VERBOSE_FETCH     = ON

-- Option: VOLE_PSI_ENABLE_SSE      = ON
-- Option: VOLE_PSI_PIC             = OFF
-- Option: VOLE_PSI_ENABLE_GMW      = ON
-- Option: VOLE_PSI_ENABLE_CPSI     = ON
-- Option: VOLE_PSI_ENABLE_OPPRF    = ON

-- Option: COPROTO_ENABLE_BOOST     = ON
-- Option: COPROTO_ENABLE_OPENSSL   = ON
-- Option: LIBOTE_ENABLE_BITPOLYMUL = ON
-- VOLEPSI_THIRDPARTY_DIR=/root/volepsi/out/install/linux
============= Building sparsehash-c11 =============
Checkout edd6f1180156e76facc1c0449da245208ab39503
'/usr/bin/git' 'checkout' 'edd6f1180156e76facc1c0449da245208ab39503'
HEAD is now at edd6f11 Merge pull request #36 from sparsehash/version
log /root/volepsi/thirdparty/log-sparsehash-c11.txt
==========================================
SPARSEHASH_INCLUDE_DIRS=/root/volepsi/out/install/linux/include
============= Building libOTe =============
libOTe Checkout 3d1ecb211a2421a670f787131ea1fb2d477ff128
'/usr/bin/git' 'checkout' '3d1ecb211a2421a670f787131ea1fb2d477ff128'
HEAD is now at 3d1ecb2 version bump
libOTe submodule
'/usr/bin/git' 'submodule' 'update' '--recursive'
libOTe Configure
'/usr/bin/cmake' '-S' '/root/volepsi/out/libOTe' '-B' '/root/volepsi/out/libOTe/out/build/linux' '-DCMAKE_INSTALL_PREFIX=/usr/local' '-DCMAKE_PREFIX_PATH=/root/volepsi/out/install/linux;' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DFETCH_AUTO=ON' '-DVERBOSE_FETCH=ON' '-DENABLE_CIRCUITS=ON' '-DENABLE_MRR=ON' '-DENABLE_IKNP=ON' '-DENABLE_SOFTSPOKEN_OT=ON' '-DENABLE_BITPOLYMUL=ON' '-DENABLE_SILENTOT=ON' '-DENABLE_SILENT_VOLE=ON' '-DENABLE_SODIUM=ON' '-DENABLE_MRR_TWIST=ON' '-DENABLE_SSE=ON' '-DCOPROTO_ENABLE_BOOST=ON' '-DCOPROTO_ENABLE_OPENSSL=ON' '-DOC_PIC=OFF' '-DOC_THIRDPARTY_CLONE_DIR=/root/volepsi/out'
-- cryptoTools options
=======================================================
-- Option: FETCH_AUTO        = ON
-- Option: VERBOSE_FETCH     = ON

-- Option: FETCH_SPAN_LITE   =
-- Option: FETCH_RELIC       =
-- Option: FETCH_SODIUM      =
-- Option: FETCH_BOOST       =

-- Option: CMAKE_BUILD_TYPE  = Release
        Release
        Debug
        RelWithDebInfo
-- Option: ENABLE_SPAN_LITE  = ON
-- Option: ENABLE_RELIC      = OFF
-- Option: ENABLE_SODIUM     = ON
-- Option: ENABLE_BOOST      = OFF

-- Option: ENABLE_CIRCUITS   = ON
-- Option: ENABLE_NET_LOG    = OFF
-- Option: ENABLE_WOLFSSL    = OFF
-- Option: ENABLE_SSE        = ON
-- Option: ENABLE_AVX        = ON
-- Option: ENABLE_BOOST      = OFF

span-lite already fetched (cryptoTools).
============= Building Sodium =============
Checkout 4e825a68baebdf058543f29762c73c17b1816ec0
'/usr/bin/git' 'checkout' '4e825a68baebdf058543f29762c73c17b1816ec0'
HEAD is now at 4e825a68 Merge branch 'master' of github.com:jedisct1/libsodium
Autogen
'./autogen.sh' '-s'
libtool is required, but wasn't found on this system
CMake Error at cryptoTools/thirdparty/fetch.cmake:35 (message):
  Autogen failed (1).

  LOG:

  vvvvvvvvvvvvv RUN Cloning https://github.com/osu-crypto/libsodium.git
  vvvvvvvvvvvv

  /usr/bin/git;clone;https://github.com/osu-crypto/libsodium.git

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  vvvvvvvvvvvvv RUN Checkout 4e825a68baebdf058543f29762c73c17b1816ec0
  vvvvvvvvvvvv

  /usr/bin/git;checkout;4e825a68baebdf058543f29762c73c17b1816ec0

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  vvvvvvvvvvvvv RUN Autogen vvvvvvvvvvvv

  ./autogen.sh;-s

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  vvvvvvvvvvvvv RUN Checkout 4e825a68baebdf058543f29762c73c17b1816ec0
  vvvvvvvvvvvv

  /usr/bin/git;checkout;4e825a68baebdf058543f29762c73c17b1816ec0

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  vvvvvvvvvvvvv RUN Autogen vvvvvvvvvvvv

  ./autogen.sh;-s

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Call Stack (most recent call first):
  cryptoTools/thirdparty/getSodium.cmake:65 (run)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:143 (include)
  cryptoTools/CMakeLists.txt:134 (include)

-- Configuring incomplete, errors occurred!
See also "/root/volepsi/out/libOTe/out/build/linux/CMakeFiles/CMakeOutput.log".
libOTe Build
'/usr/bin/cmake' '--build' '/root/volepsi/out/libOTe/out/build/linux' '--config' 'Release'
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.
libOTe Install
'/usr/bin/cmake' '--install' '/root/volepsi/out/libOTe/out/build/linux' '--config' 'Release' '--prefix' '/root/volepsi/out/install/linux'
CMake Error: Error processing file: /root/volepsi/out/libOTe/out/build/linux/cmake_install.cmake
log /root/volepsi/thirdparty/log-libOTe.txt
==========================================
CMake Error at cmake/findDependancies.cmake:57 (find_package):
  By not providing "FindlibOTe.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libOTe", but
  CMake did not find one.

  Could not find a package configuration file provided by "libOTe" with any
  of the following names:

    libOTeConfig.cmake
    libote-config.cmake

  Add the installation prefix of "libOTe" to CMAKE_PREFIX_PATH or set
  "libOTe_DIR" to a directory containing one of the above files.  If "libOTe"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/findDependancies.cmake:71 (FIND_LIBOTE)
  CMakeLists.txt:14 (include)**

-- Configuring incomplete, errors occurred!
See also "/root/volepsi/out/build/linux/CMakeFiles/CMakeOutput.log".
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.

I changed the container and redeployed it, but the same error still occurred. The current environment is ubuntu:20.04.
Could you give me some advice? 
Look forward to your reply.

**Comment by ladnir** [comment]
as per the error you posted
```
libtool is required, but wasn't found on this system
```

**Comment by WandQ** [comment]
Thanks for your reply. The problem was solved after I executed the following command:
`apt-get install libtool`
